0x41424142/qualysdk

- README.md
- docs/index.md
- docs/vmdr.md
- qualyspy/base/call_schema.py
- qualyspy/vmdr/__init__.py
- qualyspy/vmdr/data_classes/__init__.py
- qualyspy/vmdr/data_classes/scanner_appliance.py
- qualyspy/vmdr/data_classes/tag.py
- qualyspy/vmdr/scanner_appliances.py
- qualyspy/vmdr/vmscans.py
- **Added v1 of get_scanner_list(). Needs work, but works.**
- **Updated docs.**
- **Finished get_scanner_list()**
> scanner list

- docs/sql.md
- qualysdk/__init__.py
- qualysdk/sql/__init__.py
- qualysdk/sql/base.py
- qualysdk/sql/supported_uploads.py
- qualysdk/sql/vmdr.py
- qualysdk/vmdr/data_classes/user.py
- qualysdk/vmdr/users.py
- **Changed static search list SQL upload function name to upload_vmdr_static_searchlists**
- **Added upload_vmdr_users**
> Add upload_vmdr_users

- docs/vmdr.md
- qualysdk/base/call_api.py
- qualysdk/vmdr/base/__init__.py
- qualysdk/vmdr/base/helpers.py
- qualysdk/vmdr/get_host_list.py
- qualysdk/vmdr/get_host_list_detections.py
Used the same pagination logic as get_hld. backend thread management moved to qualysdk/vmdr/base/helpers. Also improved thread printing by acquiring lock on all prints and outputting the function the thread is targeting in prints.
> Threaded vmdr.get_host_list!!!

- README.md
- docs/index.md
- pyproject.toml
- qualysdk/gav/hosts.py
- qualysdk/gav/query_assets.py
- qualysdk/sql/gav.py
- **Changed gav host's softwareListData to a BaseList of dicts. SQL upload still converts to string.**
> Changed GAV host's softwareListData to BaseList[dict]

- docs/was.md
- poetry.lock
- pyproject.toml
- qualysdk/base/call_schema.py
- qualysdk/was/__init__.py
- qualysdk/was/base/filter_mappings.py
- qualysdk/was/base/parse_kwargs.py
- qualysdk/was/base/service_requests.py
- qualysdk/was/webapps.py
- **Added create_webapp with some kwarg support**
- **Added create_webapp with some kwarg support**
- **Added tag ID as option to create_webapp**
> Add was.create_webapp

- docs/sql.md
- docs/totalcloud.md
- pyproject.toml
- qualysdk/base/call_schema.py
- qualysdk/sql/__init__.py
- qualysdk/sql/totalcloud.py
- qualysdk/totalcloud/__init__.py
- qualysdk/totalcloud/data_classes/RemediationActivity.py
- qualysdk/totalcloud/data_classes/__init__.py
- qualysdk/totalcloud/remediation_log.py
- **Added totalcloud.get_remediation_activities**
- **Bump version**
> Added totalcloud.get_remediation_activities and sql.upload_totalcloud_remediation_activities

- poetry.lock
- pyproject.toml
- qualysdk/base/xml_parser.py
- qualysdk/totalcloud/data_classes/Evaluation.py
Fixes CodeFactor issues found in https://github.com/0x41424142/qualysdk/issues/150
> CodeFactor Security Findings

- docs/quickstart.md
- docs/sql.md
- docs/was.md
- poetry.lock
- pyproject.toml
- qualysdk/cli_updater.py
- qualysdk/sql/__init__.py
- qualysdk/sql/was.py
- qualysdk/was/__init__.py
- qualysdk/was/authentication_records.py
- qualysdk/was/data_classes/Comment.py
- qualysdk/was/data_classes/WebAppAuthFormRecord.py
- qualysdk/was/data_classes/WebAppAuthRecord.py
- qualysdk/was/data_classes/WebAppAuthServerRecord.py
- qualysdk/was/data_classes/__init__.py
- **Added was.get_authentication_record_details**
- **Added sql upload for was auth records**
- **Added qualysdk-updater CLI tool**
> Added authentication record pulls to WAS, SQL uploads for auth records, added qualysdk-updater CLI tool

- docs/was.md
- pyproject.toml
- qualysdk/base/printutils.py
- qualysdk/sql/gav.py
- qualysdk/was/__init__.py
- qualysdk/was/authentication_records.py
- **Added was.get_authentication_records_verbose**
- **Fixed bug in GAV SQL upload**
- **Added printutils**
> Added printutils, more auth record WAS calls

- docs/was.md
- pyproject.toml
- qualysdk/cli_updater.py
- qualysdk/was/__init__.py
- qualysdk/was/authentication_records.py
- qualysdk/was/base/filter_mappings.py
- **Fixed stdout redirect on updater**
- **Added delete_authentication_record**
> Added delete_authentication_record, fixed updater cli

- docs/sql.md
- docs/totalcloud.md
- pyproject.toml
- qualysdk/sql/__init__.py
- qualysdk/sql/totalcloud.py
- qualysdk/totalcloud/data_classes/AWSResources.py
- qualysdk/totalcloud/data_classes/AzureResources.py
- qualysdk/totalcloud/data_classes/resource_mappings.py
- qualysdk/totalcloud/get_inventory.py
- qualysdk/totalcloud/get_resource_details.py
- **Added Azure VIRTUAL_MACHINE and WEB_APP to totalcloud.get_inventory/totalcloud.get_resource_details, wrote sql.upload for these objects**
> Added Azure VM and web apps to totalcloud

- .gitignore
- docs/patch.md
- docs/sql.md
- pyproject.toml
- qualysdk/__init__.py
- qualysdk/base/__init__.py
- qualysdk/base/call_schemas/pm_schema.py
- qualysdk/base/csv_export.py
- qualysdk/base/json_export.py
- qualysdk/cli/qualysdk_gav.py
- qualysdk/cli/qualysdk_pm.py
- qualysdk/pm/__init__.py
- qualysdk/pm/base/page_limit.py
- qualysdk/pm/data_classes/JobResultSummary.py
- qualysdk/pm/data_classes/PMAsset.py
- qualysdk/pm/data_classes/__init__.py
- qualysdk/pm/jobs.py
- qualysdk/sql/__init__.py
- qualysdk/sql/pm.py
- **Added PM job results, SQL upload, qualysdk-pm CLI tool, fixes**
> Added qualysdk-pm, getting job results, sql uploads for PM

- docs/patch.md
- docs/sql.md
- pyproject.toml
- qualysdk/base/call_schemas/pm_schema.py
- qualysdk/pm/__init__.py
- qualysdk/pm/data_classes/JobResultSummary.py
- qualysdk/pm/data_classes/PMRun.py
- qualysdk/pm/data_classes/__init__.py
- qualysdk/pm/jobs.py
- qualysdk/sql/__init__.py
- qualysdk/sql/pm.py
- **Added pm.get_job_runs**
- **Added sql.upload_pm_job_runs, added jobId to PMRun class**
- **Multithreaded pm.list_jobs**
> Multithread list_jobs, sql uploads, get_job_runs

- README.md
- docs/cert.md
- docs/index.md
- docs/sql.md
- mkdocs.yml
- pyproject.toml
- qualysdk/__init__.py
- qualysdk/base/call_api.py
- qualysdk/base/call_schema.py
- qualysdk/base/call_schemas/__init__.py
- qualysdk/base/call_schemas/certview_schema.py
- qualysdk/cert/__init__.py
- qualysdk/cert/data_classes/Asset.py
- qualysdk/cert/data_classes/Certificate.py
- qualysdk/cert/data_classes/__init__.py
- qualysdk/cert/list_certs.py
- qualysdk/pm/jobs.py
- qualysdk/sql/__init__.py
- qualysdk/sql/cert.py
- **Added list_certs from certview module, sql.upload_cert_certs (uploads certs and assets to 2 tables)**
- **Added missing files**
> Added certificate view module, sql uploads

- docs/cert.md
- docs/patch.md
- pyproject.toml
- qualysdk/cli/qualysdk_cert.py
- qualysdk/cli/qualysdk_pm.py
- qualysdk/pm/jobs.py
- **Added qualysdk-cert CLI tool**
- **clean up docs**
> Add qualysdk-cert CLI tool

- docs/patch.md
- docs/sql.md
- pyproject.toml
- qualysdk/base/call_schemas/pm_schema.py
- qualysdk/cli/qualysdk_pm.py
- qualysdk/pm/__init__.py
- qualysdk/pm/data_classes/PMVulnerability.py
- qualysdk/pm/jobs.py
- qualysdk/pm/vulnerabilities.py
- qualysdk/sql/__init__.py
- qualysdk/sql/base.py
- qualysdk/sql/pm.py
- qualysdk/vmdr/query_kb.py
- **Added pm.delete_job, changed return of create_job to string of job UUID**
- **Added pm.change_job_status**
- **Small refactor of return logic in pm**
- **Added pm.lookup_cves, fixed docstring in vmdr.query_kb**
- **Added qualysdk-pm lookup_cves**
- **added sql.upload_pm_cves, added 'sqlite3' as accepted value to sql.db_connect**
> Added multiple PM endpoints, PM CLI command, fixed KB pull in VMDR, added SQL support for pm.lookup_cves

- poetry.lock
- pyproject.toml
- qualysdk/pm/data_classes/Job.py
- qualysdk/pm/data_classes/JobResultSummary.py
- qualysdk/pm/data_classes/PMAsset.py
- qualysdk/pm/jobs.py
- qualysdk/pm/vulnerabilities.py
- **Fixed bugs in PM obj creation, bumped numpy/mkdocs-material**
> Bug fixes in PM, bumped numpy & mkdocs-material

- poetry.lock
- pyproject.toml
- qualysdk/cs/data_classes/container.py
- qualysdk/sql/cs.py
- **added new fields to container dataclass**
- **updated mkdocs, numpy**
> Updates for container security

- docs/containersecurity.md
- docs/json.md
- docs/sql.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
- qualysdk/base/base_class.py
- qualysdk/base/base_list.py
- qualysdk/base/call_schemas/cs_schema.py
- qualysdk/cs/__init__.py
- qualysdk/cs/container/container_calls.py
- qualysdk/cs/data_classes/container.py
- qualysdk/cs/data_classes/software.py
- qualysdk/cs/data_classes/vulnerability.py
- qualysdk/sql/__init__.py
- qualysdk/sql/base.py
- qualysdk/sql/cs.py
- qualysdk/vmdr/data_classes/hosts.py
- **Fixed IP bug in vmdr host**
- **Added getting software list in container security, fixed bug in container class datetime**
- **added sql.upload_cs_software**
- **Added new fields to container class**
- **refactor of the container class**
- **added vuln count call to container security**
- **Added getting vulns in CS, added experimental JSON support for all dataclasses/baselists**
- **added support for uploading json into certain columns on SQL upload**
> Upgrades - more container security calls, added support for JSON serialization on dataclasses

- docs/tagging.md
- pyproject.toml
- qualysdk/cli/qualysdk_tag.py
- qualysdk/tagging/__init__.py
- qualysdk/tagging/calls.py
- **Added get_tag_details to tagging**
- **added create_tag to tagging and CLI**
- **added delete_tag to tagging, CLI**
- **updated documentation for deleting tags**
- **Added update tag, cli**
- **fixed docs**
- **doc update**
> Finished Tagging APIs
